window.__DOCS__ = [
    {
        name: "abs",
        signature: "abs(number)",
        category: "A",
        description: "Возвращает абсолютное значение числа.",
        class_name: "",
        parameters: [
            {
                name: "number",
                type_hint: "int | float | complex",
                required: true,
                positional_only: true,
                description: "Число для вычисления модуля",
            },
        ],
        returns: {
            type: "int | float | complex",
            description: "Абсолютное значение",
        },
        examples: [
            { code: "abs(-5)", output: "5" },
            { code: "abs(3+4j)", output: "5.0" },
        ],
        is_class: false,
        url: "https://docs.python.org/3/library/functions.html#abs",
    },
    {
        name: "all",
        signature: "all(iterable)",
        category: "A",
        description:
            "Возвращает True, если все элементы итерируемого объекта истинны.",
        class_name: "",
        parameters: [
            {
                name: "iterable",
                type_hint: "Iterable",
                required: true,
                positional_only: true,
                description: "Итерируемый объект для проверки",
            },
        ],
        returns: { type: "bool", description: "Результат логической проверки" },
        examples: [
            { code: "all([True, 1, 'hello'])", output: "True" },
            { code: "all([0, 1, 2])", output: "False" },
        ],
        is_class: false,
        url: "https://docs.python.org/3/library/functions.html#all",
    },
    {
        name: "any",
        signature: "any(iterable)",
        category: "A",
        description:
            "Возвращает True, если хотя бы один элемент итерируемого объекта истинен.",
        class_name: "",
        parameters: [
            {
                name: "iterable",
                type_hint: "Iterable",
                required: true,
                positional_only: true,
                description: "Итерируемый объект для проверки",
            },
        ],
        returns: { type: "bool", description: "Результат логической проверки" },
        examples: [
            { code: "any([0, False, None])", output: "False" },
            { code: "any([0, 1, None])", output: "True" },
        ],
        is_class: false,
        url: "https://docs.python.org/3/library/functions.html#any",
    },
    {
        name: "len",
        signature: "len(obj)",
        category: "L",
        description: "Возвращает количество элементов в объекте.",
        class_name: "",
        parameters: [
            {
                name: "obj",
                type_hint: "Sized",
                required: true,
                positional_only: true,
                description: "Объект с поддержкой протокола длины",
            },
        ],
        returns: { type: "int", description: "Количество элементов" },
        examples: [
            { code: "len([1, 2, 3])", output: "3" },
            { code: "len('Python')", output: "6" },
        ],
        is_class: false,
        url: "https://docs.python.org/3/library/functions.html#len",
    },
    {
        name: "print",
        signature:
            "print(*objects, sep=' ', end='\\n', file=None, flush=False)",
        category: "P",
        description: "Печатает объекты в текстовый поток.",
        class_name: "",
        parameters: [
            {
                name: "objects",
                required: true,
                variadic: true,
                description: "Выводимое на экран значение",
            },
            {
                name: "sep",
                type_hint: "str",
                required: false,
                default_value: "' '",
                keyword_only: true,
                description: "Разделитель",
            },
            {
                name: "end",
                type_hint: "str",
                required: false,
                default_value: "'\\n'",
                keyword_only: true,
                description: "Завершающая строка",
            },
            {
                name: "file",
                type_hint: "object",
                required: false,
                default_value: "None",
                keyword_only: true,
                description: "Файловый объект",
            },
            {
                name: "flush",
                type_hint: "bool",
                required: false,
                default_value: "False",
                keyword_only: true,
                description: "Принудительный сброс буфера",
            },
        ],
        returns: { type: "None", description: "Не возвращает значения" },
        examples: [
            { code: "print('Hello', 'World', sep='-')", output: "Hello-World" },
        ],
        is_class: false,
        url: "https://docs.python.org/3/library/functions.html#print",
    },
    {
        name: "input",
        signature: "input(prompt=None)",
        category: "I",
        description: "Считывает строку из ввода.",
        class_name: "",
        parameters: [
            {
                name: "prompt",
                type_hint: "str | None",
                required: false,
                positional_only: true,
                description: "Строка-подсказка",
            },
        ],
        returns: { type: "str", description: "Введённая строка" },
        examples: [{ code: "name = input('Имя: ')", output: "Имя: Анна ⏎" }],
        is_class: false,
        url: "https://docs.python.org/3/library/functions.html#input",
    },
    {
        name: "int",
        signature: "int(x=0) | int(x, base=10)",
        category: "I",
        description: "Возвращает целочисленный объект.",
        class_name: "",
        parameters: [
            {
                name: "x",
                type_hint: "int | float | str",
                required: false,
                positional_only: true,
                description: "Значение для преобразования",
            },
            {
                name: "base",
                type_hint: "int",
                required: false,
                positional_only: true,
                description: "Система счисления",
            },
        ],
        returns: { type: "int", description: "Целое число" },
        examples: [
            { code: "int('42')", output: "42" },
            { code: "int('1010', 2)", output: "10" },
        ],
        is_class: true,
        url: "https://docs.python.org/3/library/functions.html#int",
    },
    {
        name: "float",
        signature: "float(x=0.0)",
        category: "F",
        description: "Возвращает число с плавающей точкой.",
        class_name: "",
        parameters: [
            {
                name: "x",
                type_hint: "int | float | str",
                required: false,
                positional_only: true,
                description: "Значение для преобразования",
            },
        ],
        returns: { type: "float", description: "Число с плавающей точкой" },
        examples: [{ code: "float('3.14')", output: "3.14" }],
        is_class: true,
        url: "https://docs.python.org/3/library/functions.html#float",
    },
    {
        name: "str",
        signature: "str(object='')",
        category: "S",
        description: "Возвращает строковую версию объекта.",
        class_name: "",
        parameters: [
            {
                name: "object",
                type_hint: "object",
                required: false,
                positional_only: true,
                description: "Объект для преобразования",
            },
        ],
        returns: { type: "str", description: "Строковое представление" },
        examples: [{ code: "str(2024)", output: "'2024'" }],
        is_class: true,
        url: "https://docs.python.org/3/library/functions.html#str",
    },
    {
        name: "range",
        signature: "range(stop) | range(start, stop[, step])",
        category: "R",
        description: "Возвращает неизменяемую последовательность чисел.",
        class_name: "",
        parameters: [
            {
                name: "start",
                type_hint: "int",
                required: false,
                positional_only: true,
                description: "Начало",
            },
            {
                name: "stop",
                type_hint: "int",
                required: true,
                positional_only: true,
                description: "Конец (не включается)",
            },
            {
                name: "step",
                type_hint: "int",
                required: false,
                positional_only: true,
                description: "Шаг",
            },
        ],
        returns: { type: "range", description: "Объект range" },
        examples: [{ code: "list(range(3))", output: "[0, 1, 2]" }],
        is_class: true,
        url: "https://docs.python.org/3/library/functions.html#range",
    },
    {
        name: "list",
        signature: "list(iterable=())",
        category: "L",
        description: "Создаёт список из итерируемого объекта.",
        class_name: "",
        parameters: [
            {
                name: "iterable",
                type_hint: "Iterable",
                required: false,
                positional_only: true,
                description: "Итерируемый объект",
            },
        ],
        returns: { type: "list", description: "Новый список" },
        examples: [{ code: "list('abc')", output: "['a', 'b', 'c']" }],
        is_class: true,
        url: "https://docs.python.org/3/library/functions.html#list",
    },
    {
        name: "dict",
        signature:
            "dict(**kwargs) | dict(mapping, **kwargs) | dict(iterable, **kwargs)",
        category: "D",
        description: "Создаёт новый словарь.",
        class_name: "",
        parameters: [
            {
                name: "mapping",
                type_hint: "Mapping",
                required: false,
                description: "Словарь или итерируемый объект пар ключ-значение",
            },
        ],
        returns: { type: "dict", description: "Новый словарь" },
        examples: [{ code: "dict(a=1, b=2)", output: "{'a': 1, 'b': 2}" }],
        is_class: true,
        url: "https://docs.python.org/3/library/functions.html#dict",
    },
    {
        name: "set",
        signature: "set(iterable=())",
        category: "S",
        description: "Создаёт новое множество.",
        class_name: "",
        parameters: [
            {
                name: "iterable",
                type_hint: "Iterable",
                required: false,
                positional_only: true,
                description: "Итерируемый объект",
            },
        ],
        returns: { type: "set", description: "Новое множество" },
        examples: [{ code: "set([1, 2, 2, 3])", output: "{1, 2, 3}" }],
        is_class: true,
        url: "https://docs.python.org/3/library/functions.html#set",
    },
    {
        name: "open",
        signature:
            "open(file, mode='r', buffering=-1, encoding=None, errors=None, newline=None, closefd=True, opener=None)",
        category: "O",
        description: "Открывает файл и возвращает файловый объект.",
        class_name: "",
        parameters: [
            {
                name: "file",
                type_hint: "str | PathLike",
                required: true,
                description: "Путь к файлу",
            },
            {
                name: "mode",
                type_hint: "str",
                required: false,
                default_value: "'r'",
                description: "Режим доступа",
            },
            {
                name: "encoding",
                type_hint: "str",
                required: false,
                default_value: "None",
                description: "Кодировка",
            },
        ],
        returns: {
            type: "TextIOWrapper | BufferedReader",
            description: "Файловый объект",
        },
        examples: [
            {
                code: "with open('data.txt', 'r', encoding='utf-8') as f: content = f.read()",
                output: "",
            },
        ],
        is_class: false,
        url: "https://docs.python.org/3/library/functions.html#open",
    },
    {
        name: "type",
        signature: "type(object)",
        category: "T",
        description: "Возвращает тип объекта.",
        class_name: "",
        parameters: [
            {
                name: "object",
                type_hint: "object",
                required: true,
                positional_only: true,
                description: "Объект для определения типа",
            },
        ],
        returns: { type: "type", description: "Тип объекта" },
        examples: [{ code: "type(42)", output: "<class 'int'>" }],
        is_class: true,
        url: "https://docs.python.org/3/library/functions.html#type",
    },
    {
        name: "isinstance",
        signature: "isinstance(object, classinfo)",
        category: "I",
        description:
            "Проверяет, является ли объект экземпляром класса или кортежа классов.",
        class_name: "",
        parameters: [
            {
                name: "object",
                type_hint: "object",
                required: true,
                positional_only: true,
                description: "Проверяемый объект",
            },
            {
                name: "classinfo",
                type_hint: "type | tuple",
                required: true,
                positional_only: true,
                description: "Класс или кортеж классов",
            },
        ],
        returns: { type: "bool", description: "Результат проверки" },
        examples: [{ code: "isinstance(42, int)", output: "True" }],
        is_class: false,
        url: "https://docs.python.org/3/library/functions.html#isinstance",
    },
    {
        name: "chr",
        signature: "chr(i)",
        category: "C",
        description: "Возвращает строку из одного символа с кодом Unicode.",
        class_name: "",
        parameters: [
            {
                name: "i",
                type_hint: "int",
                required: true,
                positional_only: true,
                description: "Код Unicode (0–0x10FFFF)",
            },
        ],
        returns: { type: "str", description: "Символ" },
        examples: [{ code: "chr(97)", output: "'a'" }],
        is_class: false,
        url: "https://docs.python.org/3/library/functions.html#chr",
    },
    {
        name: "ord",
        signature: "ord(c)",
        category: "O",
        description: "Возвращает код Unicode символа.",
        class_name: "",
        parameters: [
            {
                name: "c",
                type_hint: "str",
                required: true,
                positional_only: true,
                description: "Символ (строка длины 1)",
            },
        ],
        returns: { type: "int", description: "Код Unicode" },
        examples: [{ code: "ord('a')", output: "97" }],
        is_class: false,
        url: "https://docs.python.org/3/library/functions.html#ord",
    },
    {
        name: "sum",
        signature: "sum(iterable, start=0)",
        category: "S",
        description: "Возвращает сумму элементов итерируемого объекта.",
        class_name: "",
        parameters: [
            {
                name: "iterable",
                type_hint: "Iterable",
                required: true,
                positional_only: true,
                description: "Итерируемый объект с числами",
            },
            {
                name: "start",
                type_hint: "int | float",
                required: false,
                default_value: "0",
                positional_only: true,
                description: "Начальное значение суммы",
            },
        ],
        returns: { type: "int | float", description: "Сумма элементов" },
        examples: [{ code: "sum([1, 2, 3])", output: "6" }],
        is_class: false,
        url: "https://docs.python.org/3/library/functions.html#sum",
    },
    {
        name: "min",
        signature:
            "min(iterable, *[, key, default]) | min(arg1, arg2, *args[, key])",
        category: "M",
        description: "Возвращает наименьший элемент.",
        class_name: "",
        parameters: [
            {
                name: "iterable",
                type_hint: "Iterable",
                required: true,
                description: "Итерируемый объект или аргументы",
            },
            {
                name: "key",
                type_hint: "function",
                required: false,
                keyword_only: true,
                description: "Функция для извлечения ключа сравнения",
            },
            {
                name: "default",
                type_hint: "object",
                required: false,
                keyword_only: true,
                description: "Значение по умолчанию для пустого итерируемого",
            },
        ],
        returns: { type: "object", description: "Наименьший элемент" },
        examples: [{ code: "min([3, 1, 4])", output: "1" }],
        is_class: false,
        url: "https://docs.python.org/3/library/functions.html#min",
    },
    {
        name: "max",
        signature:
            "max(iterable, *[, key, default]) | max(arg1, arg2, *args[, key])",
        category: "M",
        description: "Возвращает наибольший элемент.",
        class_name: "",
        parameters: [
            {
                name: "iterable",
                type_hint: "Iterable",
                required: true,
                description: "Итерируемый объект или аргументы",
            },
            {
                name: "key",
                type_hint: "function",
                required: false,
                keyword_only: true,
                description: "Функция для извлечения ключа сравнения",
            },
            {
                name: "default",
                type_hint: "object",
                required: false,
                keyword_only: true,
                description: "Значение по умолчанию для пустого итерируемого",
            },
        ],
        returns: { type: "object", description: "Наибольший элемент" },
        examples: [{ code: "max([3, 1, 4])", output: "4" }],
        is_class: false,
        url: "https://docs.python.org/3/library/functions.html#max",
    },
    {
        name: "round",
        signature: "round(number, ndigits=None)",
        category: "R",
        description:
            "Округляет число до заданного количества знаков после запятой.",
        class_name: "",
        parameters: [
            {
                name: "number",
                type_hint: "float | int",
                required: true,
                positional_only: true,
                description: "Число для округления",
            },
            {
                name: "ndigits",
                type_hint: "int",
                required: false,
                positional_only: true,
                description: "Количество знаков после запятой",
            },
        ],
        returns: { type: "int | float", description: "Округлённое число" },
        examples: [{ code: "round(3.14159, 2)", output: "3.14" }],
        is_class: false,
        url: "https://docs.python.org/3/library/functions.html#round",
    },
    {
        name: "pow",
        signature: "pow(base, exp, mod=None)",
        category: "P",
        description:
            "Возводит base в степень exp, по модулю mod (если указан).",
        class_name: "",
        parameters: [
            {
                name: "base",
                type_hint: "int | float",
                required: true,
                positional_only: true,
                description: "Основание",
            },
            {
                name: "exp",
                type_hint: "int | float",
                required: true,
                positional_only: true,
                description: "Показатель степени",
            },
            {
                name: "mod",
                type_hint: "int",
                required: false,
                positional_only: true,
                description: "Модуль для вычисления",
            },
        ],
        returns: {
            type: "int | float",
            description: "Результат возведения в степень",
        },
        examples: [
            { code: "pow(2, 3)", output: "8" },
            { code: "pow(2, 3, 5)", output: "3" },
        ],
        is_class: false,
        url: "https://docs.python.org/3/library/functions.html#pow",
    },
    {
        name: "strip",
        signature: "str.strip([chars])",
        category: "S",
        description:
            "Возвращает копию строки с удалёнными ведущими и замыкающими символами.",
        class_name: "str",
        parameters: [
            {
                name: "chars",
                type_hint: "str | None",
                required: false,
                description:
                    "Набор символов для удаления (по умолчанию — пробельные)",
            },
        ],
        returns: { type: "str", description: "Обработанная строка" },
        examples: [
            { code: "'  hello  '.strip()", output: "'hello'" },
            { code: "'www.example.com'.strip('wcm.')", output: "'example'" },
        ],
        is_class: false,
        url: "https://docs.python.org/3/library/stdtypes.html#str.strip",
    },
    {
        name: "split",
        signature: "str.split(sep=None, maxsplit=-1)",
        category: "S",
        description: "Разбивает строку на список подстрок по разделителю.",
        class_name: "str",
        parameters: [
            {
                name: "sep",
                type_hint: "str | None",
                required: false,
                description: "Разделитель (по умолчанию — любой пробел)",
            },
            {
                name: "maxsplit",
                type_hint: "int",
                required: false,
                default_value: "-1",
                description: "Максимальное число разбиений",
            },
        ],
        returns: { type: "list[str]", description: "Список подстрок" },
        examples: [{ code: "'a,b,c'.split(',')", output: "['a', 'b', 'c']" }],
        is_class: false,
        url: "https://docs.python.org/3/library/stdtypes.html#str.split",
    },
    {
        name: "join",
        signature: "str.join(iterable)",
        category: "S",
        description:
            "Объединяет строки из итерируемого объекта, используя строку как разделитель.",
        class_name: "str",
        parameters: [
            {
                name: "iterable",
                type_hint: "Iterable[str]",
                required: true,
                description: "Итерируемый объект со строками",
            },
        ],
        returns: { type: "str", description: "Объединённая строка" },
        examples: [{ code: "'-'.join(['a', 'b', 'c'])", output: "'a-b-c'" }],
        is_class: false,
        url: "https://docs.python.org/3/library/stdtypes.html#str.join",
    },
    {
        name: "lower",
        signature: "str.lower()",
        category: "S",
        description: "Возвращает копию строки в нижнем регистре.",
        class_name: "str",
        parameters: [],
        returns: { type: "str", description: "Строка в нижнем регистре" },
        examples: [{ code: "'HELLO'.lower()", output: "'hello'" }],
        is_class: false,
        url: "https://docs.python.org/3/library/stdtypes.html#str.lower",
    },
    {
        name: "upper",
        signature: "str.upper()",
        category: "S",
        description: "Возвращает копию строки в верхнем регистре.",
        class_name: "str",
        parameters: [],
        returns: { type: "str", description: "Строка в верхнем регистре" },
        examples: [{ code: "'hello'.upper()", output: "'HELLO'" }],
        is_class: false,
        url: "https://docs.python.org/3/library/stdtypes.html#str.upper",
    },
    {
        name: "replace",
        signature: "str.replace(old, new, count=-1)",
        category: "S",
        description: "Возвращает копию строки с заменой подстрок.",
        class_name: "str",
        parameters: [
            {
                name: "old",
                type_hint: "str",
                required: true,
                description: "Подстрока для замены",
            },
            {
                name: "new",
                type_hint: "str",
                required: true,
                description: "Новая подстрока",
            },
            {
                name: "count",
                type_hint: "int",
                required: false,
                default_value: "-1",
                description: "Максимальное число замен",
            },
        ],
        returns: { type: "str", description: "Строка с заменами" },
        examples: [
            {
                code: "'hello world'.replace('world', 'Python')",
                output: "'hello Python'",
            },
        ],
        is_class: false,
        url: "https://docs.python.org/3/library/stdtypes.html#str.replace",
    },
    {
        name: "find",
        signature: "str.find(sub[, start[, end]])",
        category: "S",
        description: "Возвращает индекс первого вхождения подстроки или -1.",
        class_name: "str",
        parameters: [
            {
                name: "sub",
                type_hint: "str",
                required: true,
                description: "Искомая подстрока",
            },
            {
                name: "start",
                type_hint: "int",
                required: false,
                description: "Начало поиска",
            },
            {
                name: "end",
                type_hint: "int",
                required: false,
                description: "Конец поиска",
            },
        ],
        returns: { type: "int", description: "Индекс вхождения или -1" },
        examples: [{ code: "'hello'.find('ll')", output: "2" }],
        is_class: false,
        url: "https://docs.python.org/3/library/stdtypes.html#str.find",
    },
    {
        name: "startswith",
        signature: "str.startswith(prefix[, start[, end]])",
        category: "S",
        description: "Проверяет, начинается ли строка с указанной подстроки.",
        class_name: "str",
        parameters: [
            {
                name: "prefix",
                type_hint: "str | tuple[str]",
                required: true,
                description: "Префикс или кортеж префиксов",
            },
            {
                name: "start",
                type_hint: "int",
                required: false,
                description: "Начало проверки",
            },
            {
                name: "end",
                type_hint: "int",
                required: false,
                description: "Конец проверки",
            },
        ],
        returns: { type: "bool", description: "Результат проверки" },
        examples: [{ code: "'hello'.startswith('he')", output: "True" }],
        is_class: false,
        url: "https://docs.python.org/3/library/stdtypes.html#str.startswith",
    },
    {
        name: "count",
        signature: "str.count(sub[, start[, end]]) | list.count(value)",
        category: "C",
        description: "Возвращает количество вхождений подстроки/значения.",
        class_name: "str",
        parameters: [
            {
                name: "sub",
                type_hint: "str",
                required: true,
                description: "Искомая подстрока или значение",
            },
            {
                name: "start",
                type_hint: "int",
                required: false,
                description: "Начало поиска",
            },
            {
                name: "end",
                type_hint: "int",
                required: false,
                description: "Конец поиска",
            },
        ],
        returns: { type: "int", description: "Количество вхождений" },
        examples: [
            { code: "'hello'.count('l')", output: "2" },
            { code: "[1,2,2,3].count(2)", output: "2" },
        ],
        is_class: false,
        url: "https://docs.python.org/3/library/stdtypes.html#str.count",
    },
    {
        name: "append",
        signature: "list.append(object)",
        category: "A",
        description: "Добавляет объект в конец списка.",
        class_name: "list",
        parameters: [
            {
                name: "object",
                type_hint: "object",
                required: true,
                positional_only: true,
                description: "Элемент для добавления",
            },
        ],
        returns: { type: "None", description: "Модифицирует список на месте" },
        examples: [
            { code: "lst = [1, 2]\nlst.append(3)\nlst", output: "[1, 2, 3]" },
        ],
        is_class: false,
        url: "https://docs.python.org/3/library/stdtypes.html#list.append",
    },
    {
        name: "pop",
        signature: "list.pop(index=-1) | dict.pop(key[, default])",
        category: "P",
        description:
            "Удаляет и возвращает элемент по индексу (список) или ключу (словарь).",
        class_name: "list",
        parameters: [
            {
                name: "index",
                type_hint: "int",
                required: false,
                default_value: "-1",
                positional_only: true,
                description: "Индекс элемента (по умолчанию последний)",
            },
        ],
        returns: { type: "object", description: "Удалённый элемент" },
        examples: [{ code: "lst = [1, 2, 3]\nlst.pop()", output: "3" }],
        is_class: false,
        url: "https://docs.python.org/3/library/stdtypes.html#list.pop",
    },
    {
        name: "insert",
        signature: "list.insert(index, object)",
        category: "I",
        description: "Вставляет объект перед указанным индексом.",
        class_name: "list",
        parameters: [
            {
                name: "index",
                type_hint: "int",
                required: true,
                positional_only: true,
                description: "Индекс для вставки",
            },
            {
                name: "object",
                type_hint: "object",
                required: true,
                positional_only: true,
                description: "Элемент для вставки",
            },
        ],
        returns: { type: "None", description: "Модифицирует список на месте" },
        examples: [
            {
                code: "lst = [1, 3]\nlst.insert(1, 2)\nlst",
                output: "[1, 2, 3]",
            },
        ],
        is_class: false,
        url: "https://docs.python.org/3/library/stdtypes.html#list.insert",
    },
    {
        name: "remove",
        signature: "list.remove(value) | set.remove(elem)",
        category: "R",
        description:
            "Удаляет первое вхождение значения (список) или элемент (множество).",
        class_name: "list",
        parameters: [
            {
                name: "value",
                type_hint: "object",
                required: true,
                positional_only: true,
                description: "Значение для удаления",
            },
        ],
        returns: {
            type: "None",
            description: "Модифицирует коллекцию на месте",
        },
        examples: [
            {
                code: "lst = [1, 2, 2, 3]\nlst.remove(2)\nlst",
                output: "[1, 2, 3]",
            },
        ],
        is_class: false,
        url: "https://docs.python.org/3/library/stdtypes.html#list.remove",
    },
    {
        name: "clear",
        signature: "list.clear() | dict.clear() | set.clear()",
        category: "C",
        description: "Удаляет все элементы из коллекции.",
        class_name: "list",
        parameters: [],
        returns: {
            type: "None",
            description: "Модифицирует коллекцию на месте",
        },
        examples: [{ code: "lst = [1, 2, 3]\nlst.clear()\nlst", output: "[]" }],
        is_class: false,
        url: "https://docs.python.org/3/library/stdtypes.html#list.clear",
    },
    {
        name: "index",
        signature: "list.index(value[, start[, end]])",
        category: "I",
        description: "Возвращает индекс первого вхождения значения.",
        class_name: "list",
        parameters: [
            {
                name: "value",
                type_hint: "object",
                required: true,
                description: "Искомое значение",
            },
            {
                name: "start",
                type_hint: "int",
                required: false,
                description: "Начало поиска",
            },
            {
                name: "end",
                type_hint: "int",
                required: false,
                description: "Конец поиска",
            },
        ],
        returns: { type: "int", description: "Индекс вхождения" },
        examples: [{ code: "[1, 2, 3].index(2)", output: "1" }],
        is_class: false,
        url: "https://docs.python.org/3/library/stdtypes.html#list.index",
    },
    {
        name: "get",
        signature: "dict.get(key, default=None)",
        category: "G",
        description:
            "Возвращает значение по ключу или default, если ключ не найден.",
        class_name: "dict",
        parameters: [
            {
                name: "key",
                type_hint: "Hashable",
                required: true,
                description: "Ключ для поиска",
            },
            {
                name: "default",
                type_hint: "object",
                required: false,
                default_value: "None",
                description: "Значение по умолчанию",
            },
        ],
        returns: { type: "object", description: "Значение или default" },
        examples: [{ code: "d = {'a': 1}\nd.get('b', 0)", output: "0" }],
        is_class: false,
        url: "https://docs.python.org/3/library/stdtypes.html#dict.get",
    },
    {
        name: "update",
        signature: "dict.update([other])",
        category: "U",
        description:
            "Обновляет словарь элементами из другого словаря или итерируемого объекта пар.",
        class_name: "dict",
        parameters: [
            {
                name: "other",
                type_hint: "Mapping | Iterable[tuple]",
                required: false,
                description: "Словарь или итерируемый объект для обновления",
            },
        ],
        returns: { type: "None", description: "Модифицирует словарь на месте" },
        examples: [
            {
                code: "d = {'a': 1}\nd.update({'b': 2})\nd",
                output: "{'a': 1, 'b': 2}",
            },
        ],
        is_class: false,
        url: "https://docs.python.org/3/library/stdtypes.html#dict.update",
    },
    {
        name: "keys",
        signature: "dict.keys()",
        category: "K",
        description: "Возвращает представление ключей словаря.",
        class_name: "dict",
        parameters: [],
        returns: { type: "dict_keys", description: "Представление ключей" },
        examples: [
            { code: "list({'a': 1, 'b': 2}.keys())", output: "['a', 'b']" },
        ],
        is_class: false,
        url: "https://docs.python.org/3/library/stdtypes.html#dict.keys",
    },
    {
        name: "values",
        signature: "dict.values()",
        category: "V",
        description: "Возвращает представление значений словаря.",
        class_name: "dict",
        parameters: [],
        returns: { type: "dict_values", description: "Представление значений" },
        examples: [
            { code: "list({'a': 1, 'b': 2}.values())", output: "[1, 2]" },
        ],
        is_class: false,
        url: "https://docs.python.org/3/library/stdtypes.html#dict.values",
    },
    {
        name: "items",
        signature: "dict.items()",
        category: "I",
        description: "Возвращает представление пар ключ-значение словаря.",
        class_name: "dict",
        parameters: [],
        returns: {
            type: "dict_items",
            description: "Представление пар ключ-значение",
        },
        examples: [{ code: "list({'a': 1}.items())", output: "[('a', 1)]" }],
        is_class: false,
        url: "https://docs.python.org/3/library/stdtypes.html#dict.items",
    },
    {
        name: "add",
        signature: "set.add(elem)",
        category: "A",
        description: "Добавляет элемент во множество.",
        class_name: "set",
        parameters: [
            {
                name: "elem",
                type_hint: "Hashable",
                required: true,
                description: "Элемент для добавления",
            },
        ],
        returns: {
            type: "None",
            description: "Модифицирует множество на месте",
        },
        examples: [
            { code: "s = {1, 2}\ns.add(3)\nprint(s)", output: "{1, 2, 3}" },
        ],
        is_class: false,
        url: "https://docs.python.org/3/library/stdtypes.html#set.add",
    },
    {
        name: "discard",
        signature: "set.discard(elem)",
        category: "D",
        description:
            "Удаляет элемент из множества, если он присутствует (не вызывает ошибку, если отсутствует).",
        class_name: "set",
        parameters: [
            {
                name: "elem",
                type_hint: "Hashable",
                required: true,
                description: "Элемент для удаления",
            },
        ],
        returns: {
            type: "None",
            description: "Модифицирует множество на месте",
        },
        examples: [
            { code: "s = {1, 2, 3}\ns.discard(2)\ns", output: "{1, 3}" },
        ],
        is_class: false,
        url: "https://docs.python.org/3/library/stdtypes.html#set.discard",
    },
    {
        name: "union",
        signature: "set.union(*others)",
        category: "U",
        description:
            "Возвращает новое множество с элементами из данного и других множеств.",
        class_name: "set",
        parameters: [
            {
                name: "others",
                variadic: true,
                description: "Другие итерируемые объекты",
            },
        ],
        returns: { type: "set", description: "Новое множество" },
        examples: [{ code: "{1, 2}.union({2, 3})", output: "{1, 2, 3}" }],
        is_class: false,
        url: "https://docs.python.org/3/library/stdtypes.html#set.union",
    },
    {
        name: "intersection",
        signature: "set.intersection(*others)",
        category: "I",
        description: "Возвращает новое множество с общими элементами.",
        class_name: "set",
        parameters: [
            {
                name: "others",
                variadic: true,
                description: "Другие итерируемые объекты",
            },
        ],
        returns: { type: "set", description: "Новое множество" },
        examples: [
            { code: "{1, 2, 3}.intersection({2, 3, 4})", output: "{2, 3}" },
        ],
        is_class: false,
        url: "https://docs.python.org/3/library/stdtypes.html#set.intersection",
    },
    {
        name: "read",
        signature: "file.read(size=-1)",
        category: "R",
        description: "Читает до size байт/символов из файла.",
        class_name: "TextIOWrapper",
        parameters: [
            {
                name: "size",
                type_hint: "int",
                required: false,
                default_value: "-1",
                description: "Количество байт/символов для чтения",
            },
        ],
        returns: { type: "str | bytes", description: "Прочитанные данные" },
        examples: [
            {
                code: "with open('file.txt') as f: content = f.read()",
                output: "",
            },
        ],
        is_class: false,
        url: "https://docs.python.org/3/library/io.html#io.TextIOWrapper.read",
    },
    {
        name: "write",
        signature: "file.write(s)",
        category: "W",
        description: "Записывает строку/байты в файл.",
        class_name: "TextIOWrapper",
        parameters: [
            {
                name: "s",
                type_hint: "str | bytes",
                required: true,
                description: "Данные для записи",
            },
        ],
        returns: {
            type: "int",
            description: "Количество записанных символов/байт",
        },
        examples: [
            {
                code: "with open('out.txt', 'w') as f: f.write('Hello')",
                output: "",
            },
        ],
        is_class: false,
        url: "https://docs.python.org/3/library/io.html#io.TextIOWrapper.write",
    },
    {
        name: "close",
        signature: "file.close()",
        category: "C",
        description: "Закрывает файл, освобождая ресурсы.",
        class_name: "TextIOWrapper",
        parameters: [],
        returns: { type: "None", description: "Не возвращает значения" },
        examples: [{ code: "f = open('file.txt')\nf.close()", output: "" }],
        is_class: false,
        url: "https://docs.python.org/3/library/io.html#io.IOBase.close",
    },
    {
        name: "seek",
        signature: "file.seek(offset, whence=0)",
        category: "S",
        description: "Перемещает указатель файла в новую позицию.",
        class_name: "TextIOWrapper",
        parameters: [
            {
                name: "offset",
                type_hint: "int",
                required: true,
                description: "Смещение в байтах/символах",
            },
            {
                name: "whence",
                type_hint: "int",
                required: false,
                default_value: "0",
                description: "0: начало, 1: текущая позиция, 2: конец",
            },
        ],
        returns: { type: "int", description: "Новая позиция указателя" },
        examples: [
            { code: "f = open('file.txt')\nf.seek(0)\nf.close()", output: "" },
        ],
        is_class: false,
        url: "https://docs.python.org/3/library/io.html#io.IOBase.seek",
    },
    {
        name: "flush",
        signature: "file.flush()",
        category: "F",
        description: "Сбрасывает внутренний буфер вывода на диск.",
        class_name: "TextIOWrapper",
        parameters: [],
        returns: { type: "None", description: "Не возвращает значения" },
        examples: [
            {
                code: "f = open('log.txt', 'w')\nf.write('Hi')\nf.flush()",
                output: "",
            },
        ],
        is_class: false,
        url: "https://docs.python.org/3/library/io.html#io.IOBase.flush",
    },
    {
        name: "group",
        signature: "Match.group([group1, ...])",
        category: "G",
        description: "Возвращает одну или несколько подгрупп совпадения.",
        class_name: "re.Match",
        parameters: [
            {
                name: "group",
                type_hint: "int | str",
                required: false,
                variadic: true,
                description: "Номер или имя группы",
            },
        ],
        returns: {
            type: "str | tuple[str]",
            description: "Строка совпадения или кортеж",
        },
        examples: [
            {
                code: "import re\nm = re.match(r'(\\w+)', 'hello')\nm.group(1)",
                output: "'hello'",
            },
        ],
        is_class: false,
        url: "https://docs.python.org/3/library/re.html#re.Match.group",
    },
    {
        name: "start",
        signature: "Match.start([group])",
        category: "S",
        description: "Возвращает начальный индекс совпадения группы.",
        class_name: "re.Match",
        parameters: [
            {
                name: "group",
                type_hint: "int | str",
                required: false,
                description: "Номер или имя группы",
            },
        ],
        returns: { type: "int", description: "Начальный индекс" },
        examples: [
            {
                code: "import re\nm = re.search('world', 'hello world')\nm.start()",
                output: "6",
            },
        ],
        is_class: false,
        url: "https://docs.python.org/3/library/re.html#re.Match.start",
    },
    {
        name: "end",
        signature: "Match.end([group])",
        category: "E",
        description: "Возвращает конечный индекс совпадения группы.",
        class_name: "re.Match",
        parameters: [
            {
                name: "group",
                type_hint: "int | str",
                required: false,
                description: "Номер или имя группы",
            },
        ],
        returns: { type: "int", description: "Конечный индекс" },
        examples: [
            {
                code: "import re\nm = re.search('world', 'hello world')\nm.end()",
                output: "11",
            },
        ],
        is_class: false,
        url: "https://docs.python.org/3/library/re.html#re.Match.end",
    },
];

window.__NAMES__ = window.__DOCS__.map((entry) => entry.name);
